### ISSUE TITLE
Some thing wrong with tf.data.Dataset.from_generator

### ISSUE THREAD

**Issue by Robinatp** [blaueck/tf-triplet-demo#1]
for python2.7, There is a wrong with the follows about the function of tf.data.Dataset.from_generator which I never use before.So i can't understand it ,coud you help me fixed it.Thank you so much!

 ([batch_size, *img_shape], [batch_size]))
                  ^
SyntaxError: invalid syntax

**Comment by blaueck** [comment]
Thank you for your interest in the code. This is because python 2 do not suppurt the syntax like *img_shape. You can change the [batch_size, *img_shape] to [batch_size, img_shape[0], img_shape[1], img_shape[2]].

**Comment by Robinatp** [comment]
OK,I got it.Thanks again very much!
